version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/github
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo: